theme: jekyll-theme-hacker
title: Teks - For your information
description: Webpage for conceptualization of neologism "teks" by Patrick Chabot Ph.D. (sociologist) and Julie Bernard Ma. (philosopher). 