theme: jekyll-theme-hacker
google-analytics: UA-223091963-2
title: On Teks
description: Conceptualization of neologism "teks" by Patrick Chabot Ph.D. (sociologist) and Julie Bernard Ma. (philosopher).
